### ISSUE TITLE
Can it record a Video playing in Chewie Player?

### ISSUE THREAD

**Issue by rdcoder33** [RanfiCD/widget_recorder#2]
I want to add an animated watermark to a video in my app.

What I am thinking to do is to use a `Stack` widget with Video Player and Animation and record that whole `Stack` widget with `widget_recorder.`

But it records only Flutter Animation. `widget_recorder` isn't recording chewie or any other video Player.

Is there any way to fix this?

**Comment by RanfiCD** [comment]
Unfortunately, that's not posible to do currently because widget_recorder uses RepaintBoundary to get the images and this method does not work with widgets that use PlatformViews, WebViews or anything outside the normal render tree.

Maybe this package can help you: [video_thumbnail](https://pub.dev/packages/video_thumbnail)
